# These values are intended for use with e.g. Minikube to demo Otomi.
charts:
  cert-manager:
    issuer: custom-ca

cluster:
  k8sVersion: '1.20'
  name: local-install
  provider: onprem

otomi:
  adminPassword: 5!sMw
  version: master
