alerts:
  email:
    critical: admins@yourdoma.in
    nonCritical: admins@yourdoma.in
  slack:
    url: https://hooks.slack.com/services/id
azure:
  monitor:
    clientId: somesecretvalue
    clientSecret: somesecretvalue
    subscriptionId: somesecretvalue
    tenantId: somesecretvalue
home:
  email:
    critical: admins@yourdoma.in
  slack:
    url: https://hooks.slack.com/services/id
kms:
  sops:
    vault:
      token: bladiebla
oidc:
  clientSecret: somesecretvalue
otomi:
  adminPassword: bladibla
smtp:
  auth_password: somesecretvalue
