# Default values for otomi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# https://helm.sh/docs/chart_template_guide/values_files/

##
##
charts:
  cert-manager:
    issuer: custom-ca
    # email: ''
    # stage: production

  external-dns:
    enabled: false
    domainFilters: []
    zoneIdFilters: []

# -- Tell otomi your cluster metadata
cluster:
  # -- Tell otomi your k8s version in advance
  k8sVersion: '1.20'
  name: 'dev'

  # -- Enter the k8s provider: aws|azure|google
  provider: ''

# -- Enter the (cloud) provider where you use its name server services for k8s? (optional)
dns:
  {}
  # provider: aws|azure|google

  # aws:
  #   accessKeySecret: '' # optional
  #   secretAccessKey: '' # optional
  #   region: eu-central-1
  #   role: '' # optional ARN, may be set explicitly if no metadata can be accessed

  # azure:
  #   aadClientId: ''
  #   aadClientSecret: ''
  #   tenantId: '' # optional
  #   subscriptionId: '' # optional

  # google:
  #   serviceAccountKey: ''
  #   project: ''

## Who encrypts your GitOps secrets?
kms:
  sops:
    provider: ''

  # aws:
  #   keys: ''
  #   accessKey: ''
  #   secretKey: ''
  #   region: ''

  # azure:
  #   keys: ''
  #   tenantID: ''
  #   clientID: ''
  #   clientSecret: ''

  # google:
  #   keys: ''
  #   accountJson: ''
  #   project: ''

  # vault:
  # token: ''

# -- Bring your own IDP, by default oidc=keycloak
oidc: {}
#   clientID: ''
#   clientSecret: ''
#   issuer: ''

#   # IDP group id used to identify global admin
#   adminGroupID: ''

#   # IDP group id used to identify team admin
#   teamAdminGroupID: ''

# -- Contains useful metadata about your environment
otomi:
  ## Set a cluster-wide admin password
  ##
  adminPassword: 5!sMw
  hasExternalIDP: false

  ## Login to a public container registry
  ##
  globalPullSecret:
    username: dockerHubUser
  #   password: ''
